# UniFi Network Application Configuration
# Using bjw-s app-template chart

controllers:
  main:
    type: deployment
    replicas: 1
    
    containers:
      main:
        image:
          repository: lscr.io/linuxserver/unifi-network-application
          tag: 9.1.120-ls92
          pullPolicy: IfNotPresent
        
        env:
          PUID: 1000
          PGID: 1000
          TZ: UTC
          MONGO_USER: unifi
          MONGO_PASS: unifipass
          MONGO_HOST: unifi-db
          MONGO_PORT: 27017
          MONGO_DBNAME: unifi
          MEM_LIMIT: 1024
          MEM_STARTUP: 1024
        
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
          limits:
            memory: 2Gi
            cpu: 1000m
      
      mongodb:
        image:
          repository: mongo
          tag: 7.0
          pullPolicy: IfNotPresent
        
        env:
          MONGO_INITDB_ROOT_USERNAME: unifi
          MONGO_INITDB_ROOT_PASSWORD: unifipass
          MONGO_INITDB_DATABASE: unifi
        
        resources:
          requests:
            memory: 512Mi
            cpu: 250m
          limits:
            memory: 1Gi
            cpu: 500m
    

service:
  main:
    type: ClusterIP
    ports:
      web-ui:
        port: 8443
        protocol: HTTPS
      stun:
        port: 3478
        protocol: UDP
      ap-discovery:
        port: 10001
        protocol: UDP
      device-comm:
        port: 8080
        protocol: TCP
      l2-discovery:
        port: 1900
        protocol: UDP
      guest-portal:
        port: 8843
        protocol: HTTPS
      mobile-speed:
        port: 6789
        protocol: TCP
      remote-syslog:
        port: 5514
        protocol: UDP
  
  mongodb:
    type: ClusterIP
    ports:
      mongodb:
        port: 27017
        protocol: TCP

persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    size: 2Gi
    accessMode: ReadWriteOnce
    storageClass: local-path
    globalMounts:
      - path: /config
        readOnly: false
  
  data:
    enabled: true
    type: persistentVolumeClaim
    size: 10Gi
    accessMode: ReadWriteOnce
    storageClass: local-path
    globalMounts:
      - path: /data/db
        readOnly: false

  mongodb:
    enabled: true
    type: persistentVolumeClaim
    size: 10Gi
    accessMode: ReadWriteOnce
    storageClass: local-path
    globalMounts:
      - path: /data/db
        readOnly: false

# Ingress configuration (optional)
ingress:
  main:
    enabled: false
    # Uncomment and configure if you want to use ingress
    # className: nginx
    # hosts:
    #   - host: unifi.yourdomain.com
    #     paths:
    #       - path: /
    #         pathType: Prefix
    #         service:
    #           name: main
    #           port: 8443

# Security Context
defaultPodOptions:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch

# Azure Key Vault configuration
azureKeyVault:
  enabled: false
  vaultName: ""
  secrets:
    username: ""
    password: ""
    database: ""

