# UniFi Network Application Configuration for k3s-new cluster

replicaCount: 1

image:
  repository: lscr.io/linuxserver/unifi-network-application
  tag: 9.1.120-ls92
  pullPolicy: IfNotPresent

# Environment variables
env:
  PUID: "1000"
  PGID: "1000"
  TZ: "UTC"
  MEM_LIMIT: "1024"
  MEM_STARTUP: "1024"

# MongoDB connection (will use secrets from Azure Key Vault)
mongodb:
  enabled: true
  host: argocd-unifi-mongodb
  port: "27017"
  image:
    repository: mongo
    tag: "7.0"
    pullPolicy: IfNotPresent
  env:
    MONGO_INITDB_ROOT_USERNAME: unifi
    MONGO_INITDB_ROOT_PASSWORD: unifipass
    MONGO_INITDB_DATABASE: unifi
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 500m
  persistence:
    storageClass: local-path
    size: 10Gi
  pod:
    nodeSelector:
      kubernetes.io/hostname: k3s-node3
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - k3s-node3

# Resources
resources:
  requests:
    memory: 1Gi
    cpu: 500m
  limits:
    memory: 2Gi
    cpu: 1000m

# Node affinity
nodeSelector:
  kubernetes.io/hostname: k3s-node3

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3s-node3

# Persistence configuration
persistence:
  config:
    enabled: true
    size: 2Gi
    storageClass: local-path
  data:
    enabled: true
    size: 10Gi
    storageClass: local-path
  mongodb:
    enabled: true
    size: 10Gi
    storageClass: local-path

# Service configuration
service:
  type: NodePort
  ports:
    ap-discovery:
      port: 10001
      nodePort: 30001
      protocol: UDP
    device-comm:
      port: 8080
      nodePort: 30180
      protocol: TCP
    guest-portal:
      port: 8843
      nodePort: 30843
      protocol: TCP
    l2-discovery:
      port: 1900
      nodePort: 30900
      protocol: UDP
    mobile-speed:
      port: 6789
      nodePort: 30789
      protocol: TCP
    remote-syslog:
      port: 5514
      nodePort: 30514
      protocol: UDP
    stun:
      port: 3478
      nodePort: 30478
      protocol: UDP
    web-ui:
      port: 8443
      nodePort: 30443
      protocol: TCP

# Security Context
defaultPodOptions:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch

# Azure Key Vault configuration
azureKeyVault:
  enabled: true
  vaultName: oohbooshvault001
  secrets:
    username: unifi-mongo-username
    password: unifi-mongo-password
    database: unifi-mongo-database