{{- if .Values.azureKeyVault.enabled }}
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: {{ include "argocd-unifi.fullname" . }}-mongo-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "argocd-unifi.labels" . | nindent 4 }}
spec:
  vault:
    name: {{ .Values.azureKeyVault.vaultName }}
    object:
      name: {{ include "argocd-unifi.fullname" . }}-mongo-credentials
      type: secret
      contentType: application/x-json
  output:
    secret:
      name: {{ include "argocd-unifi.fullname" . }}-mongo-credentials
      type: Opaque
---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: {{ include "argocd-unifi.fullname" . }}-mongo-username
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "argocd-unifi.labels" . | nindent 4 }}
spec:
  vault:
    name: {{ .Values.azureKeyVault.vaultName }}
    object:
      name: {{ .Values.azureKeyVault.secrets.username }}
      type: secret
  output:
    secret:
      name: {{ include "argocd-unifi.fullname" . }}-mongo-username
      type: Opaque
      dataKey: username
---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: {{ include "argocd-unifi.fullname" . }}-mongo-password
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "argocd-unifi.labels" . | nindent 4 }}
spec:
  vault:
    name: {{ .Values.azureKeyVault.vaultName }}
    object:
      name: {{ .Values.azureKeyVault.secrets.password }}
      type: secret
  output:
    secret:
      name: {{ include "argocd-unifi.fullname" . }}-mongo-password
      type: Opaque
      dataKey: password
---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: {{ include "argocd-unifi.fullname" . }}-mongo-database
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "argocd-unifi.labels" . | nindent 4 }}
spec:
  vault:
    name: {{ .Values.azureKeyVault.vaultName }}
    object:
      name: {{ .Values.azureKeyVault.secrets.database }}
      type: secret
  output:
    secret:
      name: {{ include "argocd-unifi.fullname" . }}-mongo-database
      type: Opaque
      dataKey: database
{{- end }}

