{{- if and .Values.mongodb.enabled (not .Values.mongodb.sidecar) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "argocd-unifi.fullname" . }}-mongodb
  labels:
    {{- include "argocd-unifi.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: mongodb
      protocol: TCP
      name: mongodb
  selector:
    {{- include "argocd-unifi.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
{{- end }}