# Persistent Volume Claims
{{- if .Values.persistence.config.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "argocd-unifi.fullname" . }}-config
  labels:
    {{- include "argocd-unifi.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.config.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size }}
{{- end }}

{{- if .Values.persistence.mongodb.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "argocd-unifi.fullname" . }}-mongodb-data
  labels:
    {{- include "argocd-unifi.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.mongodb.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.mongodb.size }}
{{- end }}
{{- if .Values.persistence.data.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "argocd-unifi.fullname" . }}-data
  labels:
    {{- include "argocd-unifi.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.data.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
{{- end }}

