apiVersion: v1
kind: Service
metadata:
  name: {{ include "argocd-unifi.fullname" . }}
  labels:
    {{- include "argocd-unifi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $name, $config := .Values.service.ports }}
    - port: {{ $config.port }}
      targetPort: {{ $name }}
      protocol: {{ $config.protocol }}
      name: {{ $name }}
      {{- if $config.nodePort }}
      nodePort: {{ $config.nodePort }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "argocd-unifi.selectorLabels" . | nindent 4 }}

